name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-18.04
    steps:
#       - run: curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Mysql/install.sh | sudo bash -s 5.7
#       - run: curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Postgres/install.sh | sudo bash
#       - run: curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Mongodb/install.sh | sudo bash
#       - run: sudo systemctl stop mysqld && curl -SsL https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/Mysql/install.sh | sudo bash -s 8.0
      - run: sudo ss -plunt
      - run: sudo apt install -q -y tree && sudo tree -d -L 3 /data
      - run: echo ${{secrets.GMAIL_ACCOUNT}}
      - run: echo 'github test' > /data/README.md
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      
      - name: Send email
        uses: dawidd6/action-send-mail@v3.4.1
        with:
          server_address: smtp.google.com
          server_port: 465
          username: ${{secrets.GMAIL_ACCOUNT}}
          password: ${{secrets.GMAIL_PASSWORD}}
          sender: Github
          subject: æµ‹è¯•æ•°æ®åº“å®‰è£…è„šæœ¬
          from: ${{secrets.GMAIL_ACCOUNT}}
          body: file:///data/README.md
          contentType: text/html
          attachments: '[{"path":"/data/README.md"}]'
          to: xiechengqiemail@163.com

